apiVersion: v1
kind: Service
metadata:
  labels:
    name: sc2afrontend
  name: sc2afrontend
spec:
  type: LoadBalancer
  ports:
    # The port that this service should serve on.
    - port: 80
      targetPort: 8080
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: sc2a